# Use the official Node.js image as the base image
FROM node:18

# Set the working directory inside the containerr
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY backend/package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the backend code to the working directory
COPY backend/ ./

# Expose the port that your backend server listens on
EXPOSE 10000

# Start the backend server
CMD ["npm", "start"]
